Adding backup option for disks and fixing issues with updating compute node when unneeded
theforeman/foreman_fog_proxmox pull request #364
Opened 2024-10-09 19:46 UTC by btoneill

* Added option for turning backup on/off from Foreman so you can keep some disks from being backed up. Otherwise if you set it on the Proxmox side a foreman update will change it back. Was unable to use a checkbox as the default for backup is a blank setting and the ActionPack stuff doesn't pass thru an unchecked checkbox. So had to make it a pull down option list.

* Removed the mac address upcase change because it causes every update of a host in Foreman to cause an update of the MAC address in proxmox because foreman uses the mac address in the format of the host and this causes it to always change if they don't match

* For some reason the code is setting the id of the network device for proxmox to be the network name the OS thinks it is. For example, OS is ens18 and proxmox is net0. The code forced ens18 to the compute_attributes which causes Foreman to always think an update needs to be done. Log for this in debug mode is "Scheduling compute instance update because id changed it's value from 'net0' (String) to 'ens18' (String)". This fixes it so it properly uses the net0 instead of getting the name of the OS network device.

2024-10-14 17:34 UTC, btoneill commented
I have cleared up the rubocop and js errors. I think it's all pushed properly. I'm new at doing this stuff thru GitHub so apologies on figuring out the process.

2024-10-16 08:14 UTC, Manisha15 commented
The tests are failing, can you please fix them.

2024-10-17 08:01 UTC, Manisha15 requested changes

2024-10-17 08:01 UTC, Manisha15 commented on webpack/components/ProxmoxServer/components/HardDisk.js
> +        options={ProxmoxComputeSelectors.proxmoxBackupsMap}
```suggestion
        info={__('Enable/disable volume backup')}
        options={ProxmoxComputeSelectors.proxmoxBackupsMap}
```

2024-10-17 08:01 UTC, Manisha15 commented on app/views/compute_resources_vms/form/proxmox/server/_volume_hard_disk.html.erb
> +    <%= checkbox_f f, :backup, :checked => (f.object.backup == '1' || f.object.backup.nil? ), :label => _('Backup'), :label_help => _('Enable/disable volume backup') %>
you can remove this line as this is an obsolete file and will be removed in next version.

2026-06-10 14:01 UTC, Manisha15 commented
closing wrt #451

2026-06-10 14:01 UTC, closed without merging